(TeX-add-style-hook "matchit"
 (function
  (lambda ()
    (LaTeX-add-bibliographies
     "gk"
     "gkpubs")
    (LaTeX-add-labels
     "methods"
     "chap:reference"
     "sec:matchit"
     "subsec:weights"
     "rnames"
     "subsec:vercontrol")
    (TeX-add-symbols
     "hlink"
     "MatchIt")
    (TeX-run-style-hooks
     "fullpage"
     "dcolumn"
     "html"
     "url"
     "epsf"
     "verbatim"
     "amssymb"
     "amsmath"
     "reqno"
     "natbib"
     "graphicx"
     "bibentry"
     "latex2e"
     "bk12"
     "book"
     "oneside"
     "letterpaper"
     "12pt"
     "intro"
     "overview"
     "preprocess"
     "balance"
     "matchit2zelig"
     "matchitref"
     "summaryref"
     "plotref"
     "mdataref"))))

